<template>
  <div class="loadingio-spinner-ellipsis-n7fcerkjpkh">
    <div class="ldio-2pyxnmbo7uk">
      <div />
      <div />
      <div />
      <div />
      <div />
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-2pyxnmbo7uk {
   0% { transform: translate(7.199999999999999px,48px) scale(0); }
  25% { transform: translate(7.199999999999999px,48px) scale(0); }
  50% { transform: translate(7.199999999999999px,48px) scale(1); }
  75% { transform: translate(48px,48px) scale(1); }
 100% { transform: translate(88.8px,48px) scale(1); }
}
@keyframes ldio-2pyxnmbo7uk-r {
   0% { transform: translate(88.8px,48px) scale(1); }
 100% { transform: translate(88.8px,48px) scale(0); }
}
@keyframes ldio-2pyxnmbo7uk-c {
   0% { background: #98c1d9 }
  25% { background: #ee6c4d }
  50% { background: #98c1d9 }
  75% { background: #ee6c4d }
 100% { background: #98c1d9 }
}
.ldio-2pyxnmbo7uk div {
  position: absolute;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  transform: translate(48px,48px) scale(1);
  background: #98c1d9;
  animation: ldio-2pyxnmbo7uk 1.923076923076923s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-2pyxnmbo7uk div:nth-child(1) {
  background: #ee6c4d;
  transform: translate(88.8px,48px) scale(1);
  animation: ldio-2pyxnmbo7uk-r 0.4807692307692307s infinite cubic-bezier(0,0.5,0.5,1), ldio-2pyxnmbo7uk-c 1.923076923076923s infinite step-start;
}.ldio-2pyxnmbo7uk div:nth-child(2) {
  animation-delay: -0.4807692307692307s;
  background: #98c1d9;
}.ldio-2pyxnmbo7uk div:nth-child(3) {
  animation-delay: -0.9615384615384615s;
  background: #ee6c4d;
}.ldio-2pyxnmbo7uk div:nth-child(4) {
  animation-delay: -1.4423076923076923s;
  background: #98c1d9;
}.ldio-2pyxnmbo7uk div:nth-child(5) {
  animation-delay: -1.923076923076923s;
  background: #ee6c4d;
}
.loadingio-spinner-ellipsis-n7fcerkjpkh {
  width: 120px;
  height: 120px;
  position: fixed;
  top: calc(50vh - 60px);
  left: calc(50vw - 60px);
  z-index: 20;
  overflow: hidden;
  background: transparent;
}
.ldio-2pyxnmbo7uk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2pyxnmbo7uk div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>